// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const prismaUrl = process.env["DATABASE_URL"] || process.env["DIRECT_URL"];

if (!prismaUrl) {
  throw new Error(
    "DATABASE_URL or DIRECT_URL environment variable is not set in .env file for Prisma CLI commands.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: prismaUrl,
  },
});
